server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fsdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: cszs1029384756
  thymeleaf:
    prefix: classpath:/page/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
mybatis:
  type-aliases-package: com.cl.flowersStore.entity
#logging:
#  level:
#    com:
#      cl:
#        flowersStore:
#          dao: debug

